//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppWebService.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriesDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CategoriesDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductsDto", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ProductsDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private System.Nullable<int> SupplierIDField;
        
        private System.Nullable<int> CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleAppWebService.ServiceReference.CategoriesDto CategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> SupplierID {
            get {
                return this.SupplierIDField;
            }
            set {
                if ((this.SupplierIDField.Equals(value) != true)) {
                    this.SupplierIDField = value;
                    this.RaisePropertyChanged("SupplierID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((this.CategoryIDField.Equals(value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ConsoleAppWebService.ServiceReference.CategoriesDto Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebServiceNorthwindSoap")]
    public interface WebServiceNorthwindSoap {
        
        // CODEGEN: Generating message contract since element name ObterCategoriaPorIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterCategoriaPorId", ReplyAction="*")]
        ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdResponse ObterCategoriaPorId(ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterCategoriaPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdResponse> ObterCategoriaPorIdAsync(ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequest request);
        
        // CODEGEN: Generating message contract since element name ObterProdutoPorIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterProdutoPorId", ReplyAction="*")]
        ConsoleAppWebService.ServiceReference.ObterProdutoPorIdResponse ObterProdutoPorId(ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterProdutoPorId", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterProdutoPorIdResponse> ObterProdutoPorIdAsync(ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequest request);
        
        // CODEGEN: Generating message contract since element name ObterListaDeCategoriasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterListaDeCategorias", ReplyAction="*")]
        ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasResponse ObterListaDeCategorias(ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterListaDeCategorias", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasResponse> ObterListaDeCategoriasAsync(ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequest request);
        
        // CODEGEN: Generating message contract since element name ObterListaDeProdutosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterListaDeProdutos", ReplyAction="*")]
        ConsoleAppWebService.ServiceReference.ObterListaDeProdutosResponse ObterListaDeProdutos(ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObterListaDeProdutos", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterListaDeProdutosResponse> ObterListaDeProdutosAsync(ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterCategoriaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterCategoriaPorId", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequestBody Body;
        
        public ObterCategoriaPorIdRequest() {
        }
        
        public ObterCategoriaPorIdRequest(ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterCategoriaPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int categoryId;
        
        public ObterCategoriaPorIdRequestBody() {
        }
        
        public ObterCategoriaPorIdRequestBody(int categoryId) {
            this.categoryId = categoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterCategoriaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterCategoriaPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdResponseBody Body;
        
        public ObterCategoriaPorIdResponse() {
        }
        
        public ObterCategoriaPorIdResponse(ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterCategoriaPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppWebService.ServiceReference.CategoriesDto ObterCategoriaPorIdResult;
        
        public ObterCategoriaPorIdResponseBody() {
        }
        
        public ObterCategoriaPorIdResponseBody(ConsoleAppWebService.ServiceReference.CategoriesDto ObterCategoriaPorIdResult) {
            this.ObterCategoriaPorIdResult = ObterCategoriaPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterProdutoPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterProdutoPorId", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequestBody Body;
        
        public ObterProdutoPorIdRequest() {
        }
        
        public ObterProdutoPorIdRequest(ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterProdutoPorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int productId;
        
        public ObterProdutoPorIdRequestBody() {
        }
        
        public ObterProdutoPorIdRequestBody(int productId) {
            this.productId = productId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterProdutoPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterProdutoPorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebService.ServiceReference.ObterProdutoPorIdResponseBody Body;
        
        public ObterProdutoPorIdResponse() {
        }
        
        public ObterProdutoPorIdResponse(ConsoleAppWebService.ServiceReference.ObterProdutoPorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterProdutoPorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppWebService.ServiceReference.ProductsDto ObterProdutoPorIdResult;
        
        public ObterProdutoPorIdResponseBody() {
        }
        
        public ObterProdutoPorIdResponseBody(ConsoleAppWebService.ServiceReference.ProductsDto ObterProdutoPorIdResult) {
            this.ObterProdutoPorIdResult = ObterProdutoPorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterListaDeCategoriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterListaDeCategorias", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequestBody Body;
        
        public ObterListaDeCategoriasRequest() {
        }
        
        public ObterListaDeCategoriasRequest(ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObterListaDeCategoriasRequestBody {
        
        public ObterListaDeCategoriasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterListaDeCategoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterListaDeCategoriasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasResponseBody Body;
        
        public ObterListaDeCategoriasResponse() {
        }
        
        public ObterListaDeCategoriasResponse(ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterListaDeCategoriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppWebService.ServiceReference.CategoriesDto[] ObterListaDeCategoriasResult;
        
        public ObterListaDeCategoriasResponseBody() {
        }
        
        public ObterListaDeCategoriasResponseBody(ConsoleAppWebService.ServiceReference.CategoriesDto[] ObterListaDeCategoriasResult) {
            this.ObterListaDeCategoriasResult = ObterListaDeCategoriasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterListaDeProdutosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterListaDeProdutos", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequestBody Body;
        
        public ObterListaDeProdutosRequest() {
        }
        
        public ObterListaDeProdutosRequest(ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObterListaDeProdutosRequestBody {
        
        public ObterListaDeProdutosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObterListaDeProdutosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObterListaDeProdutosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleAppWebService.ServiceReference.ObterListaDeProdutosResponseBody Body;
        
        public ObterListaDeProdutosResponse() {
        }
        
        public ObterListaDeProdutosResponse(ConsoleAppWebService.ServiceReference.ObterListaDeProdutosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObterListaDeProdutosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleAppWebService.ServiceReference.ProductsDto[] ObterListaDeProdutosResult;
        
        public ObterListaDeProdutosResponseBody() {
        }
        
        public ObterListaDeProdutosResponseBody(ConsoleAppWebService.ServiceReference.ProductsDto[] ObterListaDeProdutosResult) {
            this.ObterListaDeProdutosResult = ObterListaDeProdutosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceNorthwindSoapChannel : ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceNorthwindSoapClient : System.ServiceModel.ClientBase<ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap>, ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap {
        
        public WebServiceNorthwindSoapClient() {
        }
        
        public WebServiceNorthwindSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceNorthwindSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceNorthwindSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceNorthwindSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdResponse ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap.ObterCategoriaPorId(ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequest request) {
            return base.Channel.ObterCategoriaPorId(request);
        }
        
        public ConsoleAppWebService.ServiceReference.CategoriesDto ObterCategoriaPorId(int categoryId) {
            ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequest inValue = new ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequest();
            inValue.Body = new ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequestBody();
            inValue.Body.categoryId = categoryId;
            ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdResponse retVal = ((ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap)(this)).ObterCategoriaPorId(inValue);
            return retVal.Body.ObterCategoriaPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdResponse> ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap.ObterCategoriaPorIdAsync(ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequest request) {
            return base.Channel.ObterCategoriaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdResponse> ObterCategoriaPorIdAsync(int categoryId) {
            ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequest inValue = new ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequest();
            inValue.Body = new ConsoleAppWebService.ServiceReference.ObterCategoriaPorIdRequestBody();
            inValue.Body.categoryId = categoryId;
            return ((ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap)(this)).ObterCategoriaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppWebService.ServiceReference.ObterProdutoPorIdResponse ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap.ObterProdutoPorId(ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequest request) {
            return base.Channel.ObterProdutoPorId(request);
        }
        
        public ConsoleAppWebService.ServiceReference.ProductsDto ObterProdutoPorId(int productId) {
            ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequest inValue = new ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequest();
            inValue.Body = new ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequestBody();
            inValue.Body.productId = productId;
            ConsoleAppWebService.ServiceReference.ObterProdutoPorIdResponse retVal = ((ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap)(this)).ObterProdutoPorId(inValue);
            return retVal.Body.ObterProdutoPorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterProdutoPorIdResponse> ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap.ObterProdutoPorIdAsync(ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequest request) {
            return base.Channel.ObterProdutoPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterProdutoPorIdResponse> ObterProdutoPorIdAsync(int productId) {
            ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequest inValue = new ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequest();
            inValue.Body = new ConsoleAppWebService.ServiceReference.ObterProdutoPorIdRequestBody();
            inValue.Body.productId = productId;
            return ((ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap)(this)).ObterProdutoPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasResponse ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap.ObterListaDeCategorias(ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequest request) {
            return base.Channel.ObterListaDeCategorias(request);
        }
        
        public ConsoleAppWebService.ServiceReference.CategoriesDto[] ObterListaDeCategorias() {
            ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequest inValue = new ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequest();
            inValue.Body = new ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequestBody();
            ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasResponse retVal = ((ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap)(this)).ObterListaDeCategorias(inValue);
            return retVal.Body.ObterListaDeCategoriasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasResponse> ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap.ObterListaDeCategoriasAsync(ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequest request) {
            return base.Channel.ObterListaDeCategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasResponse> ObterListaDeCategoriasAsync() {
            ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequest inValue = new ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequest();
            inValue.Body = new ConsoleAppWebService.ServiceReference.ObterListaDeCategoriasRequestBody();
            return ((ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap)(this)).ObterListaDeCategoriasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppWebService.ServiceReference.ObterListaDeProdutosResponse ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap.ObterListaDeProdutos(ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequest request) {
            return base.Channel.ObterListaDeProdutos(request);
        }
        
        public ConsoleAppWebService.ServiceReference.ProductsDto[] ObterListaDeProdutos() {
            ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequest inValue = new ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequest();
            inValue.Body = new ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequestBody();
            ConsoleAppWebService.ServiceReference.ObterListaDeProdutosResponse retVal = ((ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap)(this)).ObterListaDeProdutos(inValue);
            return retVal.Body.ObterListaDeProdutosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterListaDeProdutosResponse> ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap.ObterListaDeProdutosAsync(ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequest request) {
            return base.Channel.ObterListaDeProdutosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppWebService.ServiceReference.ObterListaDeProdutosResponse> ObterListaDeProdutosAsync() {
            ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequest inValue = new ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequest();
            inValue.Body = new ConsoleAppWebService.ServiceReference.ObterListaDeProdutosRequestBody();
            return ((ConsoleAppWebService.ServiceReference.WebServiceNorthwindSoap)(this)).ObterListaDeProdutosAsync(inValue);
        }
    }
}
